// Generated by @wagmi/cli@1.1.0 on 05/06/2023 at 11:46:28
import {
  useContractRead,
  UseContractReadConfig,
  useContractWrite,
  UseContractWriteConfig,
  usePrepareContractWrite,
  UsePrepareContractWriteConfig,
  useContractEvent,
  UseContractEventConfig,
} from 'wagmi'
import {
  ReadContractResult,
  WriteContractMode,
  PrepareWriteContractResult,
} from 'wagmi/actions'

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// MyToken
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const myTokenABI = [
  { stateMutability: 'nonpayable', type: 'constructor', inputs: [] },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'owner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'spender',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'value',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'Approval',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'from', internalType: 'address', type: 'address', indexed: true },
      { name: 'to', internalType: 'address', type: 'address', indexed: true },
      {
        name: 'value',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'Transfer',
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [
      { name: 'owner', internalType: 'address', type: 'address' },
      { name: 'spender', internalType: 'address', type: 'address' },
    ],
    name: 'allowance',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'spender', internalType: 'address', type: 'address' },
      { name: 'amount', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'approve',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'account', internalType: 'address', type: 'address' }],
    name: 'balanceOf',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'decimals',
    outputs: [{ name: '', internalType: 'uint8', type: 'uint8' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'spender', internalType: 'address', type: 'address' },
      { name: 'subtractedValue', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'decreaseAllowance',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'spender', internalType: 'address', type: 'address' },
      { name: 'addedValue', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'increaseAllowance',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: 'amount', internalType: 'uint256', type: 'uint256' }],
    name: 'mint',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'name',
    outputs: [{ name: '', internalType: 'string', type: 'string' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'symbol',
    outputs: [{ name: '', internalType: 'string', type: 'string' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'totalSupply',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'to', internalType: 'address', type: 'address' },
      { name: 'amount', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'transfer',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'from', internalType: 'address', type: 'address' },
      { name: 'to', internalType: 'address', type: 'address' },
      { name: 'amount', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'transferFrom',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
  },
] as const

export const myTokenAddress =
  '0x27f00FcFd68ABfDeF701D65Ca44e42c92e33D509' as const

export const myTokenConfig = {
  address: myTokenAddress,
  abi: myTokenABI,
} as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// React
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link myTokenABI}__.
 */
export function useMyTokenRead<
  TFunctionName extends string,
  TSelectData = ReadContractResult<typeof myTokenABI, TFunctionName>,
>(
  config: Omit<
    UseContractReadConfig<typeof myTokenABI, TFunctionName, TSelectData>,
    'abi' | 'address'
  > = {} as any,
) {
  return useContractRead({
    abi: myTokenABI,
    address: myTokenAddress,
    ...config,
  } as UseContractReadConfig<typeof myTokenABI, TFunctionName, TSelectData>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link myTokenABI}__ and `functionName` set to `"allowance"`.
 */
export function useMyTokenAllowance<
  TFunctionName extends 'allowance',
  TSelectData = ReadContractResult<typeof myTokenABI, TFunctionName>,
>(
  config: Omit<
    UseContractReadConfig<typeof myTokenABI, TFunctionName, TSelectData>,
    'abi' | 'address' | 'functionName'
  > = {} as any,
) {
  return useContractRead({
    abi: myTokenABI,
    address: myTokenAddress,
    functionName: 'allowance',
    ...config,
  } as UseContractReadConfig<typeof myTokenABI, TFunctionName, TSelectData>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link myTokenABI}__ and `functionName` set to `"balanceOf"`.
 */
export function useMyTokenBalanceOf<
  TFunctionName extends 'balanceOf',
  TSelectData = ReadContractResult<typeof myTokenABI, TFunctionName>,
>(
  config: Omit<
    UseContractReadConfig<typeof myTokenABI, TFunctionName, TSelectData>,
    'abi' | 'address' | 'functionName'
  > = {} as any,
) {
  return useContractRead({
    abi: myTokenABI,
    address: myTokenAddress,
    functionName: 'balanceOf',
    ...config,
  } as UseContractReadConfig<typeof myTokenABI, TFunctionName, TSelectData>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link myTokenABI}__ and `functionName` set to `"decimals"`.
 */
export function useMyTokenDecimals<
  TFunctionName extends 'decimals',
  TSelectData = ReadContractResult<typeof myTokenABI, TFunctionName>,
>(
  config: Omit<
    UseContractReadConfig<typeof myTokenABI, TFunctionName, TSelectData>,
    'abi' | 'address' | 'functionName'
  > = {} as any,
) {
  return useContractRead({
    abi: myTokenABI,
    address: myTokenAddress,
    functionName: 'decimals',
    ...config,
  } as UseContractReadConfig<typeof myTokenABI, TFunctionName, TSelectData>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link myTokenABI}__ and `functionName` set to `"name"`.
 */
export function useMyTokenName<
  TFunctionName extends 'name',
  TSelectData = ReadContractResult<typeof myTokenABI, TFunctionName>,
>(
  config: Omit<
    UseContractReadConfig<typeof myTokenABI, TFunctionName, TSelectData>,
    'abi' | 'address' | 'functionName'
  > = {} as any,
) {
  return useContractRead({
    abi: myTokenABI,
    address: myTokenAddress,
    functionName: 'name',
    ...config,
  } as UseContractReadConfig<typeof myTokenABI, TFunctionName, TSelectData>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link myTokenABI}__ and `functionName` set to `"symbol"`.
 */
export function useMyTokenSymbol<
  TFunctionName extends 'symbol',
  TSelectData = ReadContractResult<typeof myTokenABI, TFunctionName>,
>(
  config: Omit<
    UseContractReadConfig<typeof myTokenABI, TFunctionName, TSelectData>,
    'abi' | 'address' | 'functionName'
  > = {} as any,
) {
  return useContractRead({
    abi: myTokenABI,
    address: myTokenAddress,
    functionName: 'symbol',
    ...config,
  } as UseContractReadConfig<typeof myTokenABI, TFunctionName, TSelectData>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link myTokenABI}__ and `functionName` set to `"totalSupply"`.
 */
export function useMyTokenTotalSupply<
  TFunctionName extends 'totalSupply',
  TSelectData = ReadContractResult<typeof myTokenABI, TFunctionName>,
>(
  config: Omit<
    UseContractReadConfig<typeof myTokenABI, TFunctionName, TSelectData>,
    'abi' | 'address' | 'functionName'
  > = {} as any,
) {
  return useContractRead({
    abi: myTokenABI,
    address: myTokenAddress,
    functionName: 'totalSupply',
    ...config,
  } as UseContractReadConfig<typeof myTokenABI, TFunctionName, TSelectData>)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link myTokenABI}__.
 */
export function useMyTokenWrite<
  TFunctionName extends string,
  TMode extends WriteContractMode = undefined,
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<typeof myTokenABI, string>['request']['abi'],
        TFunctionName,
        TMode
      >
    : UseContractWriteConfig<typeof myTokenABI, TFunctionName, TMode> & {
        abi?: never
      } = {} as any,
) {
  return useContractWrite<typeof myTokenABI, TFunctionName, TMode>({
    abi: myTokenABI,
    address: myTokenAddress,
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link myTokenABI}__ and `functionName` set to `"approve"`.
 */
export function useMyTokenApprove<TMode extends WriteContractMode = undefined>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof myTokenABI,
          'approve'
        >['request']['abi'],
        'approve',
        TMode
      > & { functionName?: 'approve' }
    : UseContractWriteConfig<typeof myTokenABI, 'approve', TMode> & {
        abi?: never
        functionName?: 'approve'
      } = {} as any,
) {
  return useContractWrite<typeof myTokenABI, 'approve', TMode>({
    abi: myTokenABI,
    address: myTokenAddress,
    functionName: 'approve',
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link myTokenABI}__ and `functionName` set to `"decreaseAllowance"`.
 */
export function useMyTokenDecreaseAllowance<
  TMode extends WriteContractMode = undefined,
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof myTokenABI,
          'decreaseAllowance'
        >['request']['abi'],
        'decreaseAllowance',
        TMode
      > & { functionName?: 'decreaseAllowance' }
    : UseContractWriteConfig<typeof myTokenABI, 'decreaseAllowance', TMode> & {
        abi?: never
        functionName?: 'decreaseAllowance'
      } = {} as any,
) {
  return useContractWrite<typeof myTokenABI, 'decreaseAllowance', TMode>({
    abi: myTokenABI,
    address: myTokenAddress,
    functionName: 'decreaseAllowance',
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link myTokenABI}__ and `functionName` set to `"increaseAllowance"`.
 */
export function useMyTokenIncreaseAllowance<
  TMode extends WriteContractMode = undefined,
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof myTokenABI,
          'increaseAllowance'
        >['request']['abi'],
        'increaseAllowance',
        TMode
      > & { functionName?: 'increaseAllowance' }
    : UseContractWriteConfig<typeof myTokenABI, 'increaseAllowance', TMode> & {
        abi?: never
        functionName?: 'increaseAllowance'
      } = {} as any,
) {
  return useContractWrite<typeof myTokenABI, 'increaseAllowance', TMode>({
    abi: myTokenABI,
    address: myTokenAddress,
    functionName: 'increaseAllowance',
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link myTokenABI}__ and `functionName` set to `"mint"`.
 */
export function useMyTokenMint<TMode extends WriteContractMode = undefined>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<typeof myTokenABI, 'mint'>['request']['abi'],
        'mint',
        TMode
      > & { functionName?: 'mint' }
    : UseContractWriteConfig<typeof myTokenABI, 'mint', TMode> & {
        abi?: never
        functionName?: 'mint'
      } = {} as any,
) {
  return useContractWrite<typeof myTokenABI, 'mint', TMode>({
    abi: myTokenABI,
    address: myTokenAddress,
    functionName: 'mint',
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link myTokenABI}__ and `functionName` set to `"transfer"`.
 */
export function useMyTokenTransfer<TMode extends WriteContractMode = undefined>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof myTokenABI,
          'transfer'
        >['request']['abi'],
        'transfer',
        TMode
      > & { functionName?: 'transfer' }
    : UseContractWriteConfig<typeof myTokenABI, 'transfer', TMode> & {
        abi?: never
        functionName?: 'transfer'
      } = {} as any,
) {
  return useContractWrite<typeof myTokenABI, 'transfer', TMode>({
    abi: myTokenABI,
    address: myTokenAddress,
    functionName: 'transfer',
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link myTokenABI}__ and `functionName` set to `"transferFrom"`.
 */
export function useMyTokenTransferFrom<
  TMode extends WriteContractMode = undefined,
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof myTokenABI,
          'transferFrom'
        >['request']['abi'],
        'transferFrom',
        TMode
      > & { functionName?: 'transferFrom' }
    : UseContractWriteConfig<typeof myTokenABI, 'transferFrom', TMode> & {
        abi?: never
        functionName?: 'transferFrom'
      } = {} as any,
) {
  return useContractWrite<typeof myTokenABI, 'transferFrom', TMode>({
    abi: myTokenABI,
    address: myTokenAddress,
    functionName: 'transferFrom',
    ...config,
  } as any)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link myTokenABI}__.
 */
export function usePrepareMyTokenWrite<TFunctionName extends string>(
  config: Omit<
    UsePrepareContractWriteConfig<typeof myTokenABI, TFunctionName>,
    'abi' | 'address'
  > = {} as any,
) {
  return usePrepareContractWrite({
    abi: myTokenABI,
    address: myTokenAddress,
    ...config,
  } as UsePrepareContractWriteConfig<typeof myTokenABI, TFunctionName>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link myTokenABI}__ and `functionName` set to `"approve"`.
 */
export function usePrepareMyTokenApprove(
  config: Omit<
    UsePrepareContractWriteConfig<typeof myTokenABI, 'approve'>,
    'abi' | 'address' | 'functionName'
  > = {} as any,
) {
  return usePrepareContractWrite({
    abi: myTokenABI,
    address: myTokenAddress,
    functionName: 'approve',
    ...config,
  } as UsePrepareContractWriteConfig<typeof myTokenABI, 'approve'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link myTokenABI}__ and `functionName` set to `"decreaseAllowance"`.
 */
export function usePrepareMyTokenDecreaseAllowance(
  config: Omit<
    UsePrepareContractWriteConfig<typeof myTokenABI, 'decreaseAllowance'>,
    'abi' | 'address' | 'functionName'
  > = {} as any,
) {
  return usePrepareContractWrite({
    abi: myTokenABI,
    address: myTokenAddress,
    functionName: 'decreaseAllowance',
    ...config,
  } as UsePrepareContractWriteConfig<typeof myTokenABI, 'decreaseAllowance'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link myTokenABI}__ and `functionName` set to `"increaseAllowance"`.
 */
export function usePrepareMyTokenIncreaseAllowance(
  config: Omit<
    UsePrepareContractWriteConfig<typeof myTokenABI, 'increaseAllowance'>,
    'abi' | 'address' | 'functionName'
  > = {} as any,
) {
  return usePrepareContractWrite({
    abi: myTokenABI,
    address: myTokenAddress,
    functionName: 'increaseAllowance',
    ...config,
  } as UsePrepareContractWriteConfig<typeof myTokenABI, 'increaseAllowance'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link myTokenABI}__ and `functionName` set to `"mint"`.
 */
export function usePrepareMyTokenMint(
  config: Omit<
    UsePrepareContractWriteConfig<typeof myTokenABI, 'mint'>,
    'abi' | 'address' | 'functionName'
  > = {} as any,
) {
  return usePrepareContractWrite({
    abi: myTokenABI,
    address: myTokenAddress,
    functionName: 'mint',
    ...config,
  } as UsePrepareContractWriteConfig<typeof myTokenABI, 'mint'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link myTokenABI}__ and `functionName` set to `"transfer"`.
 */
export function usePrepareMyTokenTransfer(
  config: Omit<
    UsePrepareContractWriteConfig<typeof myTokenABI, 'transfer'>,
    'abi' | 'address' | 'functionName'
  > = {} as any,
) {
  return usePrepareContractWrite({
    abi: myTokenABI,
    address: myTokenAddress,
    functionName: 'transfer',
    ...config,
  } as UsePrepareContractWriteConfig<typeof myTokenABI, 'transfer'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link myTokenABI}__ and `functionName` set to `"transferFrom"`.
 */
export function usePrepareMyTokenTransferFrom(
  config: Omit<
    UsePrepareContractWriteConfig<typeof myTokenABI, 'transferFrom'>,
    'abi' | 'address' | 'functionName'
  > = {} as any,
) {
  return usePrepareContractWrite({
    abi: myTokenABI,
    address: myTokenAddress,
    functionName: 'transferFrom',
    ...config,
  } as UsePrepareContractWriteConfig<typeof myTokenABI, 'transferFrom'>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link myTokenABI}__.
 */
export function useMyTokenEvent<TEventName extends string>(
  config: Omit<
    UseContractEventConfig<typeof myTokenABI, TEventName>,
    'abi' | 'address'
  > = {} as any,
) {
  return useContractEvent({
    abi: myTokenABI,
    address: myTokenAddress,
    ...config,
  } as UseContractEventConfig<typeof myTokenABI, TEventName>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link myTokenABI}__ and `eventName` set to `"Approval"`.
 */
export function useMyTokenApprovalEvent(
  config: Omit<
    UseContractEventConfig<typeof myTokenABI, 'Approval'>,
    'abi' | 'address' | 'eventName'
  > = {} as any,
) {
  return useContractEvent({
    abi: myTokenABI,
    address: myTokenAddress,
    eventName: 'Approval',
    ...config,
  } as UseContractEventConfig<typeof myTokenABI, 'Approval'>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link myTokenABI}__ and `eventName` set to `"Transfer"`.
 */
export function useMyTokenTransferEvent(
  config: Omit<
    UseContractEventConfig<typeof myTokenABI, 'Transfer'>,
    'abi' | 'address' | 'eventName'
  > = {} as any,
) {
  return useContractEvent({
    abi: myTokenABI,
    address: myTokenAddress,
    eventName: 'Transfer',
    ...config,
  } as UseContractEventConfig<typeof myTokenABI, 'Transfer'>)
}
